<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class PurchaseLetter extends Model
{
    use HasFactory;

    protected $table = 'Cash_In_Payment_Report_1732091816';
    public $timestamps = false; // ⬅️ disable created_at / updated_at

    protected $fillable = [
        'purchaseletter_id',
        'Cluster',
        'Block',
        'Unit',
        'CustomerName',
        'PurchaseDate',
        'LunasDate',
        'is_ppndtp',
        'persen_ppndtp',
        'harga_netto',
        'TotalPPN',
        'harga_bbnsertifikat',
        'harga_bajb',
        'harga_bphtb',
        'harga_administrasi',
        'harga_paket_tambahan',
        'harga_admsubsidi',
        'biaya_asuransi',
        'HrgJualTotal',
        'disc_collection',
        'HrgJualTotalminDiscColl',
        'TypePembelian',
        'bank_induk',
        'KPP',
        'JenisKPR',
        'Salesman',
        'Member',
        'tanggal_akad',
        'persen_progress_bangun',
        'type_unit',
        'Amount_Before_Jan_2024',
        'Piutang_Before_Jan_2024',
        'Payment_Before_Jan_2024',
        'Jan_2024_DueDate',
        'Jan_2024_Type',
        'Jan_2024_Piutang',
        'Jan_2024_CairDate',
        'Jan_2024_Payment',
        'Feb_2024_DueDate',
        'Feb_2024_Type',
        'Feb_2024_Piutang',
        'Feb_2024_CairDate',
        'Feb_2024_Payment',
        'Mar_2024_DueDate',
        'Mar_2024_Type',
        'Mar_2024_Piutang',
        'Mar_2024_CairDate',
        'Mar_2024_Payment',
        'Apr_2024_DueDate',
        'Apr_2024_Type',
        'Apr_2024_Piutang',
        'Apr_2024_CairDate',
        'Apr_2024_Payment',
        'May_2024_DueDate',
        'May_2024_Type',
        'May_2024_Piutang',
        'May_2024_CairDate',
        'May_2024_Payment',
        'Jun_2024_DueDate',
        'Jun_2024_Type',
        'Jun_2024_Piutang',
        'Jun_2024_CairDate',
        'Jun_2024_Payment',
        'Jul_2024_DueDate',
        'Jul_2024_Type',
        'Jul_2024_Piutang',
        'Jul_2024_CairDate',
        'Jul_2024_Payment',
        'Aug_2024_DueDate',
        'Aug_2024_Type',
        'Aug_2024_Piutang',
        'Aug_2024_CairDate',
        'Aug_2024_Payment',
        'Sep_2024_DueDate',
        'Sep_2024_Type',
        'Sep_2024_Piutang',
        'Sep_2024_CairDate',
        'Sep_2024_Payment',
        'Oct_2024_DueDate',
        'Oct_2024_Type',
        'Oct_2024_Piutang',
        'Oct_2024_CairDate',
        'Oct_2024_Payment',
        'Piutang_After_Oct_2024',
        'Payment_After_Oct_2024',
        'YTD_sd_Oct_2024',
        'YTD_bayar_Oct_2024',
        'selisih',
        'dari_1_sampai_30_DP',
        'dari_31_sampai_60_DP',
        'dari_61_sampai_90_DP',
        'diatas_90_DP',
        'lebih_bayar',
    ];
}
